# Generated by Django 4.0.5 on 2022-07-22 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facture_telp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('userName', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('password', models.IntegerField()),
            ],
        ),
    ]
